spring:
  cloud:
    stream:
      bindings:
        addDiscountToProduct-in-0:
          destination: poc.product-service # Kafka topic for input
        addDiscountToProduct-out-0:
          destination: poc.discount-service # Kafka topic for output
      kafka:
        binder:
          brokers: localhost:9092 # Kafka broker
    config:
      uri: http://localhost:8888/discount-service-prod.yml # Config server URI
      fail-fast: true
  config:
    import:
      - "configserver:http://localhost:8888" # Config server URI
  application:
    name: discount-service
#  profiles:
#    active: prod

server:
  port: 9090

#logging:
#  level:
#    org.springframework.cloud.config: DEBUG
#    org.springframework: DEBUG